# Generated by Django 4.2.5 on 2023-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_empinfo_dept_remove_empinfo_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='dept',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='pic',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='eid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
