# Generated by Django 4.2.5 on 2023-09-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_empinfo_dept_empinfo_pic_alter_empinfo_eid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='empinfo',
            name='pic',
        ),
    ]
