# Generated by Django 4.2.5 on 2023-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_empinfo_dept_remove_empinfo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('timein', models.CharField(max_length=30)),
                ('timeout', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
