# Generated by Django 4.2.5 on 2023-09-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empinfo'),
        ),
    ]
