# Generated by Django 4.2.5 on 2023-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_attendance_timein_alter_attendance_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
