# Generated by Django 4.2.5 on 2023-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_empinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='dept',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empinfo',
            name='designation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
