# Generated by Django 4.2.5 on 2023-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_empinfo_dept_empinfo_designation_alter_empinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='designation',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
