# Generated by Django 4.2.5 on 2023-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_empinfo_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='workinghr',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='dept',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='designation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
