# Generated by Django 4.2.5 on 2023-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_attendance_workinghr_alter_empinfo_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admininfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password2', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
